services:
    redis:
        image: redis:7-alpine
        container_name: redis
        volumes:
            - redis_data:/data
        restart: unless-stopped
        command: redis-server --loglevel warning
        env_file:
            - .env

    aiobot:
        build:
            context: .
        container_name: aiobot
        depends_on:
            - redis
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - ./src/app/database:/bot_app/src/app/database
            - ./logs:/bot_app/logs/

volumes:
    redis_data:
